app/routes.php
<?php

Event::listen('illuminate.query', function () {
    Log::info('SQL', func_get_args());
});

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::group(['before' => ['auth', 'is_admin'], 'prefix' => 'admin'], function () {
    Route::get('/', ['uses' => 'AdminController@index', 'as' => 'admin']);
    Route::resource('parameters', 'ParametersController');
    Route::resource('parameters.parameter_values', 'ParameterValuesController');
    Route::resource('levels', 'LevelsController');
    Route::resource('activities', 'ActivitiesController');
    Route::resource('actions', 'ActionsController');
    Route::resource('medals', 'MedalsController');
    Route::resource('medals.advance_medals', 'AdvanceMedalsController');
    Route::resource('medals.medal_boosters', 'MedalBoostersController');
    #Route::resource('advance_medals.medal_boosters', 'MedalBoostersController');
    Route::resource('roles', 'RolesController');
    Route::resource('prizes', 'PrizesController');

    Route::resource('books', 'AdminBooksController', ['except' => ['destroy']]);
    Route::resource('publications', 'PublicationsController');
    Route::resource('orders', 'AdminOrdersController');

    Route::get('shipment_statuses', ['uses' => 'AdminOrdersController@shipment_statuses', 'as' => 'orders.shipment_statuses']);
    Route::get('orders/{order}/shipment_update/{shipment}', ['uses' => 'AdminOrdersController@shipment_update', 'as' => 'orders.shipment_update']);
});

Route::group(['before' => ['auth']], function () {

    Route::get('settings', ['uses' => 'UsersController@settings', 'as' => 'user.settings']);
    Route::get('notifications', ['uses' => 'UsersController@notifications', 'as' => 'notifications']);
    Route::get('medals', ['uses' => 'UsersController@medals', 'as' => 'user.medals']);

    Route::get('users/{users}/publications/{url}/update',['uses' => 'UserPublicationsController@update', 'as' => 'users.publications.update']);
    Route::get('users/{users}/publications/sold',['uses' => 'UserPublicationsController@sold', 'as' => 'users.publications.sold']);
    Route::post('cropPhoto/{id}',['uses' => 'UserPublicationsController@cropPhoto', 'as' => 'cropPhoto']);
    Route::post('rotatePhoto/{id}',['uses' => 'UserPublicationsController@rotatePhoto', 'as' => 'rotatePhoto']);
    Route::any('removePhoto/{id}',['uses' => 'UserPublicationsController@removePhoto', 'as' => 'removePhoto']);
    Route::post('addToCart', ['uses' => 'ShoppingCartController@addToCart', 'as' => 'add_to_cart']);
    Route::post('removeFromCart/{id}', ['uses' => 'ShoppingCartController@removeFromCart', 'as' => 'remove_from_cart']);
    Route::get('cart', ['uses' => 'ShoppingCartController@cart', 'as' => 'cart']);
    Route::get('carts', ['uses' => 'ShoppingCartController@index', 'as' => 'carts']);
    Route::get('carts/{id}', ['uses' => 'ShoppingCartController@show', 'as' => 'carts.show']);
    Route::post('transaction', ['uses' => 'ShoppingCartController@transaction', 'as' => 'transaction']);
    Route::resource('messages', 'MessagesController', ['except' => ['create', 'edit', 'update', 'destroy']]);
    Route::resource('orders', 'OrdersController', ['only' => ['index', 'show']]);
    Route::get('exchanges', ['uses' => 'ExchageController@index', 'as' => 'exchanges']);
    Route::get('exchanges/{id}', ['uses' => 'ExchageController@show']);
    Route::post('exchanges/{id}/accept', ['uses' => 'ExchageController@accept']);
    Route::post('exchanges/{id}/reject', ['uses' => 'ExchageController@reject']);
    Route::get('exchanges/{id}/payment', ['uses' => 'ExchageController@payment']);
    Route::post('exchange', ['uses' => 'ExchageController@store', 'as' => 'exchange']);
    Route::get('for_exchange', ['uses' => 'ExchageController@for_exchange', 'as' => 'for_exchange']);
    Route::post('books/{id}/recommend', ['uses' => 'BooksController@recommend', 'as' => 'recommend']);
    Route::post('books/{id}/user_read_status', ['uses' => 'BooksController@user_read_status', 'as' => 'book_user_read_status']);

});

Route::resource('publications', 'PublicationsController');
Route::resource('users.publications', 'UserPublicationsController');
Route::resource('books.publications', 'BookPublicationsController');
Route::get('login', ['uses' => 'UserSessionController@create', 'as' => 'login']);
Route::post('login', 'UserSessionController@store');

Route::get('login/{provider}', ['uses' => 'ConnectController@connect', 'as' => 'social.login']);

Route::get('logout', ['uses' => 'UserSessionController@destroy', 'as' => 'logout']);
if (Auth::check()) {
    Route::get('/', ['uses' => 'HomeController@showMarket', 'as' => 'home']);
} else {
    Route::get('/', ['uses' => 'HomeController@showHome', 'as' => 'home']);
}
Route::get('home', ['uses' => 'HomeController@showHome', 'as' => 'named_home']);
Route::get('market', ['uses' => 'HomeController@showMarket', 'as' => 'market']);
Route::any('search', ['uses' => 'HomeController@search', 'as' => 'search']);

Route::get('signup', ['uses' => 'UsersController@create', 'as' => 'signup']);

//Route::get('mail', ['uses' => 'MailController@send', 'as' => 'send']);
/*Route::get('send_test_email', function(){
    Mail::send('emails.registro', array('key' => 'value'), function($message)
    {
        $message->subject('Bienvenido a la gran experiencia');
        $message->from(env('CONTACT_MAIL'), env('CONTACT_NAME'));
        $message->to('luis02lopez@hotmail.com');
    });
});
*/
//Route::get('send', ['uses' => 'MailController@send', 'as' => 'send'] );

Route::get('payu_response', ['uses' => 'PayUController@response','as' => 'payu_response']);
Route::post('payu_confirm', ['uses' => 'PayUController@confirmation','as' => 'payu_confirm']);

Route::post('users/{username}/completedTour', ['uses' => 'UsersController@completedTour', 'as' => 'users.completed_tour']);
Route::post('users/{username}/comments', ['uses' => 'UsersController@comments', 'as' => 'users.comments']);
Route::any('users/{username}/relationships', ['uses' => 'UsersController@relationships', 'as' => 'users.relationships']);
Route::post('users/{username}/friends', ['uses' => 'UsersController@friends', 'as' => 'users.friends']);
Route::post('users/{username}/requestfriend', ['uses' => 'UsersController@requestFriend', 'as' => 'users.requestfriend']);
Route::post('users/{username}/update_friend_request', ['uses' => 'UsersController@updateFriendRequest', 'as' => 'users.update_friend_request']);
Route::resource('users', 'UsersController', ['except' => ['create']]);
Route::resource('users.bags', 'BagsController');

Route::resource('BookComments', 'BookCommentsController');
Route::resource('books.ratings', 'RatingsController');

Route::resource('books', 'BooksController');
Route::resource('authors', 'AuthorsController');

Route::resource('allcategories', 'MainCategoriesController');
Route::resource('categories', 'CategoriesController');

Route::get('img/medals/{file_name}', function ($file_name)
{
    $file = storage_path() . "/cache/img/medals/$file_name";
    return Response::download($file);
});

Route::get('img/publication/{id}/{file_name}', function ($id, $file_name)
{
    $file = storage_path() . "/cache/img/publication/$id/$file_name";
    return Response::download($file);
});
Route::get('site/terms', ['uses' => 'HomeController@showTerms', 'as' => 'terms']);
Route::get('site/privacy', ['uses' => 'HomeController@showPrivacy', 'as' => 'privacy']);
Route::get('howpublish', ['uses' => 'HomeController@showHowpublish', 'as' => 'howpublish']);
Route::get('registro', ['uses' => 'HomeController@ShowRegistro', 'as' => 'registro']);
Route::controller('password', 'RemindersController');
Route::get('users/{username}/upload', ['uses' => 'ImgurController@showUpload', 'as' => 'upload']);
Route::post('/uploadedimg', ['uses' => 'ImgurController@uploadimg', 'as' => 'uploadimg']);
Route::get('support', ['uses' => 'MailController@showSupport', 'as' => 'support']);
Route::post('supportmail', ['uses' => 'MailController@supportmail', 'as' => 'supportmail']);
Route::get('bug', ['uses' => 'MailController@showBug', 'as' => 'bug']);
Route::post('bugmail', ['uses' => 'MailController@bugmail', 'as' => 'bugmail']);
Route::get('publications/create',['uses' => 'UserPublicationsController@create2', 'as' => 'users.publications.create2']);
Route::post('users2',['uses' => 'UsersController@store2', 'as' => 'users.store2']);

app/controllers/PublicationsController.php
<?php

class PublicationsController extends BaseController {

	/**
	 * Display a listing of bookpublications
	 *
	 * @return Response
	 */
	public function index() {
		$bookpublications = BookPublication::all();

		/*$data = [
			'title' => BookPublication::$title,
			'model' => BookPublication::$model,
			'actions' => BookPublication::$actions,
			'elements' => $bookpublications,
			'keys' => BookPublication::$grid_attrs
		];*/
		$data = [
			'bookpublications' => $bookpublications,
		];

		return View::make('publications', $data);
	}

	/**
	 * Show the form for creating a new bookpublication
	 *
	 * @return Response
	 */
	public function create() {
		$data = [
			'location' => 'BookPublication',
			'page_header' => 'Create BookPublication',
			'model' => BookPublication::$model,
			'attrs' => BookPublication::$form_attrs
		];
		return View::make('kinbu.form', $data);
	}

	/**
	 * Store a newly created bookpublication in storage.
	 *
	 * @return Response
	 */
	public function store() {
		$validator = Validator::make($data = Input::all(), BookPublication::$rules);

		if ($validator->fails())
		{
			return Redirect::back()->withErrors($validator)->withInput();
		}

		BookPublication::create($data);

		return Redirect::route('publications.index');
	}

	/**
	 * Display the specified bookpublication.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id) {
		$bookpublication = BookPublication::findOrFail($id);

		$data = [
			'location' => 'BookPublication',
			'page_header' => 'BookPublication Details',
			'model' => BookPublication::$model,
			'element' => $bookpublication,
			'keys' => BookPublication::$grid_attrs
		];

		return View::make('kinbu.item', $data);
	}

	/**
	 * Show the form for editing the specified bookpublication.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id) {
		$bookpublication = BookPublication::find($id);

		$data = [
			'location' => 'BookPublication',
			'page_header' => 'Edit BookPublication',
			'model' => BookPublication::$model,
			'element' => $bookpublication,
			'attrs' => BookPublication::$form_attrs
		];

		return View::make('kinbu.form', $data);
	}

	/**
	 * Update the specified bookpublication in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id) {
		$bookpublication = BookPublication::findOrFail($id);

		$validator = Validator::make($data = Input::all(), BookPublication::$rules);

		if ($validator->fails())
		{
			return Redirect::back()->withErrors($validator)->withInput();
		}

		$bookpublication->update($data);

		return Redirect::route('publications.index');
	}

	/**
	 * Remove the specified bookpublication from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id) {
		BookPublication::destroy($id);

		return Redirect::route('publications.index');
	}

}

app/views/publications/index.blade.php
@extends('...default')

@section('location')
    Publicaciones de
    @if(isset($user))
        {{ $user->username }}
    {{-- @elseif(isset($book))
        {{ $book->title }}
        --}}
    @endif

@stop

@section('addedcss')
@parent
<style>
    .publication {
        margin: 16px;
    }
    .publication-content {
        margin-left: 160px;
    }
    .column-title {
        text-align: center;
    }
</style>
@stop

@section('content')
<section class="main-body">
    <div class="container">
        <h4>Publicaciones de
            @if(isset($user))
                {{ $user->username }}
            @elseif(isset($book))
                {{ $book->title }}
            @endif
        </h4>
        <div class="row">
            <div class="col-md-6">
                <h5 class="column-title">A la venta <span class="badge">{{ $on_sale->count() }}</span></h5>
                @forelse($on_sale as $key => $publication)
                <div class="row">
                    <div class="publication">
                    @if(isset($user))
                        <a href="{{ route('users.publications.show', [$user->username, $publication->url]) }}"
                            class="btn btn-default" style="text-align: left; display: block">
                            {{ $publication->image }}
                            <div class="publication-content">
                                <h4>{{ $publication->published_book_title }}</h4>
                                <ul class="list-unstyled">
                                    <li><strong>Precio:</strong> ${{ number_format($publication->price,0,',','.') }}</li>
                                    <li><strong>Estado:</strong> {{ $publication->book_state_description }}</li>
                                    <li><strong>Tapa:</strong> {{ $publication->cover_description }}</li>
                                    <li><strong>Cantidad:</strong> {{ $publication->amount }}</li>
                                </ul>
                            </div>
                            <div class="clearfix"></div>
                        </a>
                     {{-- @elseif(isset($book))
                        <a href="{{ route('users.publications.show', ['publications'=>$publication->url, 'users'=>$publication->user->username]) }}"
                            class="btn btn-default" style="text-align: left; display: block">
                            {{ {{ $publication->image }} }}
                            <div class="publication-content">
                                <h4>{{ $publication->user->name }} <small>Nivel</small> <span class="badge">{{ $publication->user->level }}</span></h4>
                                <ul class="list-unstyled">
                                    <li><strong>Precio:</strong> ${{ number_format($publication->price,0,',','.') }}</li>
                                    <li><strong>Estado:</strong> {{ $publication->book_state_description }}</li>
                                    <li><strong>Cover:</strong> {{ $publication->cover_description }}</li>
                                    <li><strong>Cantidad:</strong> {{ $publication->amount }}</li>
                                </ul>
                            </div>
                            <div class="clearfix"></div>
                        </a> --}}
                    @endif
                    </div>
                </div>
                @empty
                <div>
                    @if(isset($user))
                        {{ $user->username }} no ha publicado
                    {{-- @elseif(isset($book))
                        {{ $publication->published_book_title }} no est&aacute; a la venta 
                        --}}
                    @endif
                </div>
                @endforelse
            </div>
            <div class="col-md-6">
                <h5 class="column-title">Intercambia <span class="badge">{{ $on_exchange->count() }}</span></h5>
                @forelse($on_exchange as $key => $publication)
                <div class="row">
                    <div class="publication">
                    @if(isset($user))
                        <a href="{{ route('users.publications.show', [$user->username, $publication->url]) }}"
                            class="btn btn-default" style="text-align: left; display: block">
                            {{ $publication->image }}
                            <div class="publication-content">
                                <h4>{{ $publication->published_book_title }}</h4>
                                <ul class="list-unstyled">
                                    @if($publication->type == 'both')
                                    <li><strong>Precio:</strong> Intercambio o ${{ number_format($publication->price,0,',','.') }}</li>
                                    @else
                                    <li><strong>Intercambio</strong></li>
                                    @endif
                                    <li><strong>Estado:</strong> {{ $publication->book_state_description }}</li>
                                    <li><strong>Tapa:</strong> {{ $publication->cover_description }}</li>
                                    <li><strong>Cantidad:</strong> {{ $publication->amount }}</li>
                                </ul>
                            </div>
                            <div class="clearfix"></div>
                        </a>
                    {{-- @elseif(isset($book))
                        <a href="{{ route('books.publications.show', [$book->id, $publication->url]) }}"
                            class="btn btn-default" style="text-align: left; display: block">
                            {{ $publication->user->getGravatar(80, 'mm', 'g', true, ['class' => 'pull-left', 'width' => 100, 'height' => 100]) }}
                            <div class="publication-content">
                                <h4>{{ $publication->user->name }} <small>Nivel</small> <span class="badge">{{ $publication->user->level }}</span></h4>
                                <ul class="list-unstyled">
                                    <li><strong>Precio:</strong> ${{ number_format($publication->price,0,',','.') }}</li>
                                    <li><strong>Estado:</strong> {{ $publication->book_state_description }}</li>
                                    <li><strong>Cover:</strong> {{ $publication->cover_description }}</li>
                                    <li><strong>Cantidad:</strong> {{ $publication->amount }}</li>
                                </ul>
                            </div>
                            <div class="clearfix"></div>
                        </a> --}}
                    @endif 
                    </div>
                </div>
                @empty
                <div>
                    @if(isset($user))
                        {{ $user->username }} no ha publicado
                    {{-- @elseif(isset($book))
                        {{ $book->title }} no est&aacute; a la venta
                        --}}
                    @endif
                </div>
                @endforelse
            </div>
        </div>
    </div>
</section>
@stop

app/views/publications/small.blade.php
<div class="col-sm-4 book" style="height: 200px">
    <a href="{{ route('users.publications.show', ['publications'=>$publication->url, 'users'=>$publication->user->username]) }}"> {{--TODO: busqueda por nombre sigue sin servir cliquear redirija a vista de publicaciion--}}
        <div class="book-cover">
            {{ $publication->image }}
            <div class="inner-book-content">
                <h4>{{ $publication->published_book_title }}</h4>
                {{-- <div class="book-rating" data-rating="{{ $book->rating() }}"></div> --}}
                <strong class="book-price" @if($publication->type == 'both') style="font-size: 15px" @endif>
                    @if(in_array($publication->type, ['exchange', 'both']))
                    Intercambio
                    @endif
                    @if($publication->type == 'both')
                    o
                    @endif
                    @if(in_array($publication->type, ['sale', 'both']))
                    Desde COP ${{ number_format($publication->price,0,',','.') }}
                    @endif
                </strong>
            </div>
        </div>
    </a>
</div>

app/views/publications/sold.blade.php
@extends('...default')

@section('location')
    Publicaciones de
    @if(isset($user))
        {{ $user->username }}
    @endif

@stop

@section('addedcss')
{{ HTML::style("css/k.css") }}
@parent
<style>
    .publication {
        margin: 16px;
    }
    .publication-content {
        margin-left: 160px;
    }
    .column-title {
        text-align: center;
    }

</style>
@stop

@section('content')
<section class="main-body" style="padding-bottom: 0;">
    <div class="container">
        <div class="row">
                <h3 class="column-title"> Tus libros vendidos <span class="badge"></span></h3>
                <br>
                <div class="publication-soldbox">
                @forelse($sold as $key => $publication)
                <div class="row">
                        <div class="col-sm-6" style="width: 20%; cursor: pointer;">{{ $publication->image }}</div>
                        <div class="col-sm-6 pull-left" style="margin-top: 10px;">
                            <ul>
                                <li><strong>Título</strong> <a href="{{ route('users.publications.show', [$user->username, $publication->url]) }}"> <span class="purple-text">{{ $publication->published_book_title }} </span></a></li>
                                <br>
                                <li><strong>Precio de venta:</strong> ${{ number_format($publication->price,0,',','.') }}</li>
                                <br>
                                <li><strong>Estado:</strong> {{ $publication->book_state_description }}</li>
                                <br>
                                <li><strong>Tapa:</strong> {{ $publication->cover_description }}</li>
                                <br>
                                <li><strong>Cantidad restante:</strong> {{ $publication->amount }}</li>
                            </ul>
                        </div>
                </div> <br/><br><br>
                @empty
                <div style="text-align: center !important;">Aún no has vendido tu primer libro, nos encargamos de todos los procesos, tú sólo <a class="purple-text" href="{{ route('users.publications.create',["users" => $user->username]) }}">publica tú libro</a> y gana dinero ayudando a tener un mundo más lector.</div>
                @endforelse
                </div>
        </div>
    </div>
</section>
@stop

app/views/publications/thumbnail.blade.php
<a href="
@if(isset($route))
{{ $route }}
@else
{{ route('users.publications.show', [$publication->user->username, $publication->url]) }}
@endif
" class="thumbnail" style="width: 246px; height: 312px;">
    {{-- $book->getCoverImg('M', 'false', true, 'Cover Image', ['class' => 'book-cover-img', 'width' => 150, 'height' => 200]) --}}
    {{ $publication->image }}
    <div class="caption">
        <h3>{{ $publication->published_book_title }}</h3>
    </div>
</a>