app/routes.php
<?php

Event::listen('illuminate.query', function () {
    Log::info('SQL', func_get_args());
});

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::group(['before' => ['auth', 'is_admin'], 'prefix' => 'admin'], function () {
    Route::get('/', ['uses' => 'AdminController@index', 'as' => 'admin']);
    Route::resource('parameters', 'ParametersController');
    Route::resource('parameters.parameter_values', 'ParameterValuesController');
    Route::resource('levels', 'LevelsController');
    Route::resource('activities', 'ActivitiesController');
    Route::resource('actions', 'ActionsController');
    Route::resource('medals', 'MedalsController');
    Route::resource('medals.advance_medals', 'AdvanceMedalsController');
    Route::resource('medals.medal_boosters', 'MedalBoostersController');
    #Route::resource('advance_medals.medal_boosters', 'MedalBoostersController');
    Route::resource('roles', 'RolesController');
    Route::resource('prizes', 'PrizesController');

    Route::resource('books', 'AdminBooksController', ['except' => ['destroy']]);
    Route::resource('publications', 'PublicationsController');
    Route::resource('orders', 'AdminOrdersController');

    Route::get('shipment_statuses', ['uses' => 'AdminOrdersController@shipment_statuses', 'as' => 'orders.shipment_statuses']);
    Route::get('orders/{order}/shipment_update/{shipment}', ['uses' => 'AdminOrdersController@shipment_update', 'as' => 'orders.shipment_update']);
});

Route::group(['before' => ['auth']], function () {

    Route::get('settings', ['uses' => 'UsersController@settings', 'as' => 'user.settings']);
    Route::get('notifications', ['uses' => 'UsersController@notifications', 'as' => 'notifications']);
    Route::get('medals', ['uses' => 'UsersController@medals', 'as' => 'user.medals']);

    Route::get('users/{users}/publications/{url}/update',['uses' => 'UserPublicationsController@update', 'as' => 'users.publications.update']);
    Route::get('users/{users}/publications/sold',['uses' => 'UserPublicationsController@sold', 'as' => 'users.publications.sold']);
    Route::post('cropPhoto/{id}',['uses' => 'UserPublicationsController@cropPhoto', 'as' => 'cropPhoto']);
    Route::post('rotatePhoto/{id}',['uses' => 'UserPublicationsController@rotatePhoto', 'as' => 'rotatePhoto']);
    Route::any('removePhoto/{id}',['uses' => 'UserPublicationsController@removePhoto', 'as' => 'removePhoto']);
    Route::post('addToCart', ['uses' => 'ShoppingCartController@addToCart', 'as' => 'add_to_cart']);
    Route::post('removeFromCart/{id}', ['uses' => 'ShoppingCartController@removeFromCart', 'as' => 'remove_from_cart']);
    Route::get('cart', ['uses' => 'ShoppingCartController@cart', 'as' => 'cart']);
    Route::get('carts', ['uses' => 'ShoppingCartController@index', 'as' => 'carts']);
    Route::get('carts/{id}', ['uses' => 'ShoppingCartController@show', 'as' => 'carts.show']);
    Route::post('transaction', ['uses' => 'ShoppingCartController@transaction', 'as' => 'transaction']);
    Route::resource('messages', 'MessagesController', ['except' => ['create', 'edit', 'update', 'destroy']]);
    Route::resource('orders', 'OrdersController', ['only' => ['index', 'show']]);
    Route::get('exchanges', ['uses' => 'ExchageController@index', 'as' => 'exchanges']);
    Route::get('exchanges/{id}', ['uses' => 'ExchageController@show']);
    Route::post('exchanges/{id}/accept', ['uses' => 'ExchageController@accept']);
    Route::post('exchanges/{id}/reject', ['uses' => 'ExchageController@reject']);
    Route::get('exchanges/{id}/payment', ['uses' => 'ExchageController@payment']);
    Route::post('exchange', ['uses' => 'ExchageController@store', 'as' => 'exchange']);
    Route::get('for_exchange', ['uses' => 'ExchageController@for_exchange', 'as' => 'for_exchange']);
    Route::post('books/{id}/recommend', ['uses' => 'BooksController@recommend', 'as' => 'recommend']);
    Route::post('books/{id}/user_read_status', ['uses' => 'BooksController@user_read_status', 'as' => 'book_user_read_status']);

});

Route::resource('publications', 'PublicationsController');
Route::resource('users.publications', 'UserPublicationsController');
Route::resource('books.publications', 'BookPublicationsController');
Route::get('login', ['uses' => 'UserSessionController@create', 'as' => 'login']);
Route::post('login', 'UserSessionController@store');

Route::get('login/{provider}', ['uses' => 'ConnectController@connect', 'as' => 'social.login']);

Route::get('logout', ['uses' => 'UserSessionController@destroy', 'as' => 'logout']);
if (Auth::check()) {
    Route::get('/', ['uses' => 'HomeController@showMarket', 'as' => 'home']);
} else {
    Route::get('/', ['uses' => 'HomeController@showHome', 'as' => 'home']);
}
Route::get('home', ['uses' => 'HomeController@showHome', 'as' => 'named_home']);
Route::get('market', ['uses' => 'HomeController@showMarket', 'as' => 'market']);
Route::any('search', ['uses' => 'HomeController@search', 'as' => 'search']);

Route::get('signup', ['uses' => 'UsersController@create', 'as' => 'signup']);

//Route::get('mail', ['uses' => 'MailController@send', 'as' => 'send']);
/*Route::get('send_test_email', function(){
    Mail::send('emails.registro', array('key' => 'value'), function($message)
    {
        $message->subject('Bienvenido a la gran experiencia');
        $message->from(env('CONTACT_MAIL'), env('CONTACT_NAME'));
        $message->to('luis02lopez@hotmail.com');
    });
});
*/
//Route::get('send', ['uses' => 'MailController@send', 'as' => 'send'] );

Route::get('payu_response', ['uses' => 'PayUController@response','as' => 'payu_response']);
Route::post('payu_confirm', ['uses' => 'PayUController@confirmation','as' => 'payu_confirm']);

Route::post('users/{username}/completedTour', ['uses' => 'UsersController@completedTour', 'as' => 'users.completed_tour']);
Route::post('users/{username}/comments', ['uses' => 'UsersController@comments', 'as' => 'users.comments']);
Route::any('users/{username}/relationships', ['uses' => 'UsersController@relationships', 'as' => 'users.relationships']);
Route::post('users/{username}/friends', ['uses' => 'UsersController@friends', 'as' => 'users.friends']);
Route::post('users/{username}/requestfriend', ['uses' => 'UsersController@requestFriend', 'as' => 'users.requestfriend']);
Route::post('users/{username}/update_friend_request', ['uses' => 'UsersController@updateFriendRequest', 'as' => 'users.update_friend_request']);
Route::resource('users', 'UsersController', ['except' => ['create']]);
Route::resource('users.bags', 'BagsController');

Route::resource('BookComments', 'BookCommentsController');
Route::resource('books.ratings', 'RatingsController');

Route::resource('books', 'BooksController');
Route::resource('authors', 'AuthorsController');

Route::resource('allcategories', 'MainCategoriesController');
Route::resource('categories', 'CategoriesController');

Route::get('img/medals/{file_name}', function ($file_name)
{
    $file = storage_path() . "/cache/img/medals/$file_name";
    return Response::download($file);
});

Route::get('img/publication/{id}/{file_name}', function ($id, $file_name)
{
    $file = storage_path() . "/cache/img/publication/$id/$file_name";
    return Response::download($file);
});
Route::get('site/terms', ['uses' => 'HomeController@showTerms', 'as' => 'terms']);
Route::get('site/privacy', ['uses' => 'HomeController@showPrivacy', 'as' => 'privacy']);
Route::get('howpublish', ['uses' => 'HomeController@showHowpublish', 'as' => 'howpublish']);
Route::get('registro', ['uses' => 'HomeController@ShowRegistro', 'as' => 'registro']);
Route::controller('password', 'RemindersController');
Route::get('users/{username}/upload', ['uses' => 'ImgurController@showUpload', 'as' => 'upload']);
Route::post('/uploadedimg', ['uses' => 'ImgurController@uploadimg', 'as' => 'uploadimg']);
Route::get('support', ['uses' => 'MailController@showSupport', 'as' => 'support']);
Route::post('supportmail', ['uses' => 'MailController@supportmail', 'as' => 'supportmail']);
Route::get('bug', ['uses' => 'MailController@showBug', 'as' => 'bug']);
Route::post('bugmail', ['uses' => 'MailController@bugmail', 'as' => 'bugmail']);
Route::get('publications/create',['uses' => 'UserPublicationsController@create2', 'as' => 'users.publications.create2']);
Route::post('users2',['uses' => 'UsersController@store2', 'as' => 'users.store2']);

app/views/market/index.blade.php
@extends('default')

@section('location')
    Market
@stop

@section('addedcss')
    @parent
    {{ HTML::style("css/market.css") }}
@stop

@section('content')

    <section class="main-body">
        <div class="container">

            <div id="carousel" class="carousel slide carousel-fade" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators hide">
                <li data-target="#carousel" data-slide-to="0" class="active"></li>
                <li data-target="#carousel" data-slide-to="1"></li>
                <li data-target="#carousel" data-slide-to="2"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <img src="https://i.imgur.com/pUKuKEQ.jpg" title="From Rita Morais Fukuoka, Japan" style="height: 280px; width: 100%;">
                    <div class="carousel-caption">
                    <p> Libros nuevos y usados con garantía.</p>
                    <p class="carousel-description lead"> Lee más, gastando menos. </p>
                    {{ Form::open(['route'=>'search', 'method'=>'get', 'class'=>'navbar-form', 'role'=>'search']) }}
                    <div class="form-group">
                        <div class="inner-addon right-addon">
                            {{ HTML::image('img/FFFFFF-0.png', 'search', ['id'=>'search-navbar', 'class' => 'icon kinbu-sprite-01 search hidden-xs', 'style'=>'bottom: 0px;']) }}

                            {{--Botón de búsqueda para pantallas tipo tablet y más pequeñas--}}
                            <button id="search-navbar" type="submit" class="btn btn-default visible-xs icon kinbu-sprite-01 search">
                            <span class="glyphicon glyphicon-search visible-xs" aria-hidden="true"></span>
                            </button>

                            {{ Form::input('search','q', null, ['id' => 'search-input', 'class'=>'form-control search-input-carousel inactive', 'placeholder'=>'Busca libros', 'size'=>'30']) }}
                        </div>
                    </div>
                    {{ Form::close() }}
                    </div>
                </div>
                <div class="item">
                    <img src="https://i.imgur.com/RS8RJGM.jpg" title="From Josh Felise. Berkeley Public Library - West Branch, Berkeley, United States (Unplash license)" style="height: 280px; width: 100%;" class="hidden-sm hidden-md hidden-lg">
                    <img src="https://i.imgur.com/g4IyRkT.jpg" title="From Josh Felise. Berkeley Public Library - West Branch, Berkeley, United States (Unplash license)" style="height: 280px; width: 100%;" class="hidden-xs">
                    <div class="carousel-caption">
                    <p> Vende libros que hayas leído. </p>
                    <p class="carousel-description lead"> Permite que hayan más libros y crea amigos. Kinbu se encarga del resto. </p>
                    @if(Auth::check())<a href="{{ route('users.publications.create',['users'=>Auth::user()->username]) }}" class="btn btn-invitation gold-btn" role="button"> <p class="gold-btn-text">Publica </p> </a>
                    @endif
                    </div>
                </div>
            </div>

            <!-- Controls -->{{--
            <a class="left carousel-control" href="#carousel" role="button" data-slide="prev">
            <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#carousel" role="button" data-slide="next">
            <span class="sr-only">Next</span>
            </a>--}}
            
            </div>
            @if(Auth::check() && ! Auth::user()->hasMedal(1))
            {{--Ocultando boton de inicio del tour con clase "hidden-xs" en tablets y pantallas más pequeñas, z-index: para que el botón se encuentre delante de los demás elementos--}}
            <div class="hidden-xs" style="position:absolute;top:50px;z-index: 3;">
                <button type="button" role="button" id="start-tour-btn" class="btn btn-md btn-tour">Descubre Kinbu</button>
            </div>
            @endif
            {{--
            <div class="jumbotron">
                <p class="text-lead text-center">Compra, vende y</p>

                <p class="text-lead text-center">comparte libros con personas</p>

                <p class="text-lead text-center">cercanas a ti.</p>
            </div>
            --}}
    

            <div id="bellow-jumbotron" class="container"></div>

            <div id="bellow-items" class="container"></div>            
            <div class="hidden-xs">@include('market.slider', [ 'title' => "Destacados en venta", 'books' => $eliteBooks])</div>
            <div class="hidden-sm hidden-md hidden-lg">@include('market.slider', [ 'title' => "Destacados en venta", 'books' => $meliteBooks])</div>
            {{-- Slider de libros de intercambio @include('market.slider', [ 'title' => "En intercambio destacados", 'books' => $exchangeBooks]) --}}
            <div class="hidden-xs">@include('market.slider2', [ 'title' => "Personas han comprado", 'books' => $recentBoughtExchanged])</div>
            <div class="hidden-sm hidden-md hidden-lg">@include('market.slider2', [ 'title' => "Personas han comprado", 'books' => $mrecentBoughtExchanged])</div>
        </div>
        <br>
    </section>

@stop
@section('addedjs')
    @parent
    <div class="hidden-xs">
    @if(Auth::check() && ! Auth::user()->hasMedal(1) )
    {{ HTML::script("/js/tour.js") }}
    @endif
    </div>
    <script type="text/javascript">
        (function ($) {
            var psliders = $(".publications-slider");
            psliders.each(function (index) {
                var pslider = $(this);
                pslider.currentView = 0;
                pslider.updateChildrenVisibility = function () {
                    var me = this;
                    me.children('.row').each(function (i) {
                        if (i != me.currentView) {
                            $(this).addClass('hidden-row');
                        } else {
                            $(this).removeClass('hidden-row');
                        }
                    });
                };
                pslider.updateChildrenVisibility();
                pslider.countRowChildren = function () {
                    return this.children('.row').length;
                };
                pslider.moveToPrevRow = function () {
                    var me = this;
                    --me.currentView;
                    if (me.currentView < 0) {
                        me.currentView = me.countRowChildren() - 1;
                    }
                    pslider.updateChildrenVisibility();
                };
                pslider.moveToNextRow = function () {
                    var me = this;
                    ++me.currentView;
                    if (me.currentView >= me.countRowChildren()) {
                        me.currentView = 0;
                    }
                    pslider.updateChildrenVisibility();
                };

                pslider.find("a.slider-arrow.left-arrow").on('click', function (e) {
                    pslider.moveToPrevRow();
                });
                pslider.find("a.slider-arrow.right-arrow").on('click', function (e) {
                    pslider.moveToNextRow();
                });
            });
        }(jQuery));
    </script>
    
    
    <script type="text/javascript">
    //Añadiendo tiempo a la transición
    $("#carousel").carousel({
        interval: 5500,
        pause: "hover"
    });
    //Pausa de carousel sí está en móvil y enfoca la barra de búsqueda
    if ($(window).width() < 768) {
        $('.search-input-carousel').focus(function(){
            $("#carousel").carousel('pause');
        }).blur(function() {
            $("#carousel").carousel('cycle');
        });
    }
    </script>
@endsection

app/views/market/slider.blade.php
<h1 class="slider-title">{{ $title }}</h1>
    {{--Sí no hay libros en el momento--}}
    @if($books->isEmpty())
        <div class="publications-slider">
            <div class="row no-market-books" style="margin-left: 30px; margin-right: 30px; text-align: center;">
                <a href="{{route('publications.create')}}" style="text-align: center; margin: auto;">
                    <div class="btn gold-btn" style="font-size: 18px; "><p class="gold-btn-text"> Publica Libros </p> </div>
                </a>
            </div>
        <a class="slider-arrow left-arrow">
        {{ HTML::image('/img/kinbu-arrow-left.svg', 'chevron-left', ['class' => 'chevron-left']) }}
        </a>
        <a class="slider-arrow right-arrow">
        {{ HTML::image('/img/kinbu-arrow-right.svg', 'chevron-right', ['class' => 'chevron-right']) }}
        </a>
        </div>
    @else
<div class="publications-slider hidden-xs">
    @foreach($books as $key => $page)
    <div class="row" style="margin-left: 30px; margin-right: 30px;">
        @foreach($page as $keyPage => $subPage)
        <div class="col-md-6">
            <div class="row">
                @foreach($subPage as $subKeyPage => $publication)
                    @include('publications.small', compact('publication'))
                @endforeach
            </div>
        </div>
        @endforeach
    </div>
    @endforeach
    <a class="slider-arrow left-arrow">
        {{ HTML::image('/img/kinbu-arrow-left.svg', 'chevron-left', ['class' => 'chevron-left']) }}
    </a>
    <a class="slider-arrow right-arrow">
        {{ HTML::image('/img/kinbu-arrow-right.svg', 'chevron-right', ['class' => 'chevron-right']) }}
    </a>
</div>
<div class="publications-slider hidden-sm hidden-md hidden-lg">
    @foreach($books as $key => $page)
    <div class="row" style="margin-left: 30px; margin-right: 30px;">
        @foreach($page as $keyPage => $subPage)
        <div class="col-md-2">
            <div class="row">
                @foreach($subPage as $subKeyPage => $publication)
                    @include('publications.small', compact('publication'))
                @endforeach
            </div>
        </div>
        @endforeach
    </div>
    @endforeach
    <a class="slider-arrow left-arrow">
        {{ HTML::image('/img/kinbu-arrow-left.svg', 'chevron-left', ['class' => 'chevron-left']) }}
    </a>
    <a class="slider-arrow right-arrow">
        {{ HTML::image('/img/kinbu-arrow-right.svg', 'chevron-right', ['class' => 'chevron-right']) }}
    </a>
</div>
@endif

app/views/market/slider2.blade.php
@section('addedcss')
    @parent
    {{ HTML::style("css/kuser.css") }}
@stop
<h1 class="slider-title">{{ $title }}</h1>
    {{--Sí no hay libros en el momento--}}
    @if($books->isEmpty())
        <div class="publications-slider">
            <div class="row no-market-books" style="margin-left: 30px; margin-right: 30px; text-align: center;">
                <a href="{{route('publications.index')}}" style="text-align: center; font-size: 18px; margin: auto;">
                    <div class="btn friends-violet-btn" style="font-size: 18px; ">Explora Libros</div>
                </a>
            </div>
        <a class="slider-arrow left-arrow">
        {{ HTML::image('/img/kinbu-arrow-left.svg', 'chevron-left', ['class' => 'chevron-left']) }}
        </a>
        <a class="slider-arrow right-arrow">
        {{ HTML::image('/img/kinbu-arrow-right.svg', 'chevron-right', ['class' => 'chevron-right']) }}
        </a>
        </div>
    @else
<div class="publications-slider hidden-xs">
    @foreach($books as $key => $page)
    <div class="row" style="margin-left: 30px; margin-right: 30px;">
        @foreach($page as $keyPage => $subPage)
        <div class="col-md-6">
            <div class="row">
                @foreach($subPage as $subKeyPage => $publication)
                    @include('publications.small', compact('publication'))
                @endforeach
            </div>
        </div>
        @endforeach
    </div>
    @endforeach
    <a class="slider-arrow left-arrow">
        {{ HTML::image('/img/kinbu-arrow-left.svg', 'chevron-left', ['class' => 'chevron-left']) }}
    </a>
    <a class="slider-arrow right-arrow">
        {{ HTML::image('/img/kinbu-arrow-right.svg', 'chevron-right', ['class' => 'chevron-right']) }}
    </a>
</div>
<div class="publications-slider hidden-sm hidden-md hidden-lg">
    @foreach($books as $key => $page)
    <div class="row" style="margin-left: 30px; margin-right: 30px;">
        @foreach($page as $keyPage => $subPage)
        <div class="col-md-2">
            <div class="row">
                @foreach($subPage as $subKeyPage => $publication)
                    @include('publications.small', compact('publication'))
                @endforeach
            </div>
        </div>
        @endforeach
    </div>
    @endforeach
    <a class="slider-arrow left-arrow">
        {{ HTML::image('/img/kinbu-arrow-left.svg', 'chevron-left', ['class' => 'chevron-left']) }}
    </a>
    <a class="slider-arrow right-arrow">
        {{ HTML::image('/img/kinbu-arrow-right.svg', 'chevron-right', ['class' => 'chevron-right']) }}
    </a>
</div>
@endif