app/routes.php
<?php

Event::listen('illuminate.query', function () {
    Log::info('SQL', func_get_args());
});

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::group(['before' => ['auth', 'is_admin'], 'prefix' => 'admin'], function () {
    Route::get('/', ['uses' => 'AdminController@index', 'as' => 'admin']);
    Route::resource('parameters', 'ParametersController');
    Route::resource('parameters.parameter_values', 'ParameterValuesController');
    Route::resource('levels', 'LevelsController');
    Route::resource('activities', 'ActivitiesController');
    Route::resource('actions', 'ActionsController');
    Route::resource('medals', 'MedalsController');
    Route::resource('medals.advance_medals', 'AdvanceMedalsController');
    Route::resource('medals.medal_boosters', 'MedalBoostersController');
    #Route::resource('advance_medals.medal_boosters', 'MedalBoostersController');
    Route::resource('roles', 'RolesController');
    Route::resource('prizes', 'PrizesController');

    Route::resource('books', 'AdminBooksController', ['except' => ['destroy']]);
    Route::resource('publications', 'PublicationsController');
    Route::resource('orders', 'AdminOrdersController');

    Route::get('shipment_statuses', ['uses' => 'AdminOrdersController@shipment_statuses', 'as' => 'orders.shipment_statuses']);
    Route::get('orders/{order}/shipment_update/{shipment}', ['uses' => 'AdminOrdersController@shipment_update', 'as' => 'orders.shipment_update']);
});

Route::group(['before' => ['auth']], function () {

    Route::get('settings', ['uses' => 'UsersController@settings', 'as' => 'user.settings']);
    Route::get('notifications', ['uses' => 'UsersController@notifications', 'as' => 'notifications']);
    Route::get('medals', ['uses' => 'UsersController@medals', 'as' => 'user.medals']);

    Route::get('users/{users}/publications/{url}/update',['uses' => 'UserPublicationsController@update', 'as' => 'users.publications.update']);
    Route::get('users/{users}/publications/sold',['uses' => 'UserPublicationsController@sold', 'as' => 'users.publications.sold']);
    Route::post('cropPhoto/{id}',['uses' => 'UserPublicationsController@cropPhoto', 'as' => 'cropPhoto']);
    Route::post('rotatePhoto/{id}',['uses' => 'UserPublicationsController@rotatePhoto', 'as' => 'rotatePhoto']);
    Route::any('removePhoto/{id}',['uses' => 'UserPublicationsController@removePhoto', 'as' => 'removePhoto']);
    Route::post('addToCart', ['uses' => 'ShoppingCartController@addToCart', 'as' => 'add_to_cart']);
    Route::post('removeFromCart/{id}', ['uses' => 'ShoppingCartController@removeFromCart', 'as' => 'remove_from_cart']);
    Route::get('cart', ['uses' => 'ShoppingCartController@cart', 'as' => 'cart']);
    Route::get('carts', ['uses' => 'ShoppingCartController@index', 'as' => 'carts']);
    Route::get('carts/{id}', ['uses' => 'ShoppingCartController@show', 'as' => 'carts.show']);
    Route::post('transaction', ['uses' => 'ShoppingCartController@transaction', 'as' => 'transaction']);
    Route::resource('messages', 'MessagesController', ['except' => ['create', 'edit', 'update', 'destroy']]);
    Route::resource('orders', 'OrdersController', ['only' => ['index', 'show']]);
    Route::get('exchanges', ['uses' => 'ExchageController@index', 'as' => 'exchanges']);
    Route::get('exchanges/{id}', ['uses' => 'ExchageController@show']);
    Route::post('exchanges/{id}/accept', ['uses' => 'ExchageController@accept']);
    Route::post('exchanges/{id}/reject', ['uses' => 'ExchageController@reject']);
    Route::get('exchanges/{id}/payment', ['uses' => 'ExchageController@payment']);
    Route::post('exchange', ['uses' => 'ExchageController@store', 'as' => 'exchange']);
    Route::get('for_exchange', ['uses' => 'ExchageController@for_exchange', 'as' => 'for_exchange']);
    Route::post('books/{id}/recommend', ['uses' => 'BooksController@recommend', 'as' => 'recommend']);
    Route::post('books/{id}/user_read_status', ['uses' => 'BooksController@user_read_status', 'as' => 'book_user_read_status']);

});

Route::resource('publications', 'PublicationsController');
Route::resource('users.publications', 'UserPublicationsController');
Route::resource('books.publications', 'BookPublicationsController');
Route::get('login', ['uses' => 'UserSessionController@create', 'as' => 'login']);
Route::post('login', 'UserSessionController@store');

Route::get('login/{provider}', ['uses' => 'ConnectController@connect', 'as' => 'social.login']);

Route::get('logout', ['uses' => 'UserSessionController@destroy', 'as' => 'logout']);
if (Auth::check()) {
    Route::get('/', ['uses' => 'HomeController@showMarket', 'as' => 'home']);
} else {
    Route::get('/', ['uses' => 'HomeController@showHome', 'as' => 'home']);
}
Route::get('home', ['uses' => 'HomeController@showHome', 'as' => 'named_home']);
Route::get('market', ['uses' => 'HomeController@showMarket', 'as' => 'market']);
Route::any('search', ['uses' => 'HomeController@search', 'as' => 'search']);

Route::get('signup', ['uses' => 'UsersController@create', 'as' => 'signup']);

//Route::get('mail', ['uses' => 'MailController@send', 'as' => 'send']);
/*Route::get('send_test_email', function(){
    Mail::send('emails.registro', array('key' => 'value'), function($message)
    {
        $message->subject('Bienvenido a la gran experiencia');
        $message->from(env('CONTACT_MAIL'), env('CONTACT_NAME'));
        $message->to('luis02lopez@hotmail.com');
    });
});
*/
//Route::get('send', ['uses' => 'MailController@send', 'as' => 'send'] );

Route::get('payu_response', ['uses' => 'PayUController@response','as' => 'payu_response']);
Route::post('payu_confirm', ['uses' => 'PayUController@confirmation','as' => 'payu_confirm']);

Route::post('users/{username}/completedTour', ['uses' => 'UsersController@completedTour', 'as' => 'users.completed_tour']);
Route::post('users/{username}/comments', ['uses' => 'UsersController@comments', 'as' => 'users.comments']);
Route::any('users/{username}/relationships', ['uses' => 'UsersController@relationships', 'as' => 'users.relationships']);
Route::post('users/{username}/friends', ['uses' => 'UsersController@friends', 'as' => 'users.friends']);
Route::post('users/{username}/requestfriend', ['uses' => 'UsersController@requestFriend', 'as' => 'users.requestfriend']);
Route::post('users/{username}/update_friend_request', ['uses' => 'UsersController@updateFriendRequest', 'as' => 'users.update_friend_request']);
Route::resource('users', 'UsersController', ['except' => ['create']]);
Route::resource('users.bags', 'BagsController');

Route::resource('BookComments', 'BookCommentsController');
Route::resource('books.ratings', 'RatingsController');

Route::resource('books', 'BooksController');
Route::resource('authors', 'AuthorsController');

Route::resource('allcategories', 'MainCategoriesController');
Route::resource('categories', 'CategoriesController');

Route::get('img/medals/{file_name}', function ($file_name)
{
    $file = storage_path() . "/cache/img/medals/$file_name";
    return Response::download($file);
});

Route::get('img/publication/{id}/{file_name}', function ($id, $file_name)
{
    $file = storage_path() . "/cache/img/publication/$id/$file_name";
    return Response::download($file);
});
Route::get('site/terms', ['uses' => 'HomeController@showTerms', 'as' => 'terms']);
Route::get('site/privacy', ['uses' => 'HomeController@showPrivacy', 'as' => 'privacy']);
Route::get('howpublish', ['uses' => 'HomeController@showHowpublish', 'as' => 'howpublish']);
Route::get('registro', ['uses' => 'HomeController@ShowRegistro', 'as' => 'registro']);
Route::controller('password', 'RemindersController');
Route::get('users/{username}/upload', ['uses' => 'ImgurController@showUpload', 'as' => 'upload']);
Route::post('/uploadedimg', ['uses' => 'ImgurController@uploadimg', 'as' => 'uploadimg']);
Route::get('support', ['uses' => 'MailController@showSupport', 'as' => 'support']);
Route::post('supportmail', ['uses' => 'MailController@supportmail', 'as' => 'supportmail']);
Route::get('bug', ['uses' => 'MailController@showBug', 'as' => 'bug']);
Route::post('bugmail', ['uses' => 'MailController@bugmail', 'as' => 'bugmail']);
Route::get('publications/create',['uses' => 'UserPublicationsController@create2', 'as' => 'users.publications.create2']);
Route::post('users2',['uses' => 'UsersController@store2', 'as' => 'users.store2']);

app/models/Order.php
<?php

class Order extends Eloquent
{
    protected $fillable = ['user_id', 'cart_id', /*'exchange_id',*/ 'transaction_id'];

    public function user() {
        return $this->belongsTo('User');
    }

    public function cart() {
        return $this->belongsTo('ShoppingCart');
    }

    public function transaction() {
        return $this->belongsTo('Transaction');
    }

    public function shipments() {
        return $this->hasMany('Shipment');
    }

    public function status()
    {
        return $this->belongsTo('ParameterValue', 'order_status');
    }

    public function getStatusAttribute()
    {
        return $this->status()->lists('description')[0];
    }

    public function updateStatus()
    {
        $shipmentsStatuses = Parameter::whereAttribute('shipment_status')->first()
            ->values()->lists('id', 'pvalue');
        $ordersStatuses = Parameter::whereAttribute('order_status')->first()
            ->values()->lists('id', 'pvalue');
        $shipments = $this->shipments()->get();
        $amountPickup = 0;
        $amountToSend = 0;
        $amountSent = 0;
        $amountReceived = 0;
        foreach ($shipments as $key => $shipment) {
            switch ($shipment->shipment_status) {
                case $shipmentsStatuses['to_send']:
                    $amountToSend = $amountToSend + 1;
                    break;
                case $shipmentsStatuses['sent']:
                    $amountSent = $amountSent + 1;
                    break;
                case $shipmentsStatuses['received']:
                    $amountReceived = $amountReceived + 1;
                    break;
                default:
                    $amountPickup = $amountPickup + 1;
                    break;
            }
        }

        if ($amountToSend > 0) {
            $this->order_status = $ordersStatuses['partial'];
        } elseif ($amountPickup == 0 && $amountSent > 0) {
            $this->order_status = $ordersStatuses['sent'];
        } elseif ($amountReceived > 0 && $amountReceived < $shipments->count()) {
            $this->order_status = $ordersStatuses['partial'];
        } elseif ($amountReceived == $shipments->count()) {
            $this->order_status = $ordersStatuses['received'];
        }

        $this->save();
        $this->touch();
        return [
            'amountPickup' => $amountPickup,
            'amountToSend' => $amountToSend,
            'amountSent' => $amountSent,
            'amountReceived' => $amountReceived,
            'total' => $shipments->count()
        ];
    }


}

app/controllers/OrdersController.php
<?php

/**
 * OrdersController
 */
class OrdersController extends BaseController
{
    protected $user;

    function __construct()
    {
        $this->user = Auth::user();
    }

    function index()
    {
        $orders = $this->user->orders;
        return View::make('orders.index')->withOrders($orders);
    }

    function show($id)
    {
        $order = $this->user->orders()->with('shipments', 'shipments.publication')->findOrFail($id);
        return View::make('orders.show')->withOrder($order);
    }

}

app/views/admin/orders/index.blade.php
@extends('default')

@section('location')
Administracion de Pedidos
@stop

@section('content')
<section class="main-body">
    <div class="container">
        <div class="row">
            <div class="col-xs-12" style="overflow:auto">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>#Pedido</th>
                            <th>Usuario</th>
                            <th>Carrito</th>
                            <th>Estado</th>
                            <th>Transacion</th>
                            <th>ID Transaccion</th>
                            <th>Fecha</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($orders as $key => $order)
                            <tr>
                                <td>{{ $order->id }}</td>
                                <td>{{ link_to_route('users.show', $order->user->name, ['users' => $order->user->username] ) }}</td>
                                <td>{{ $order->cart_id }}</td>
                                <td>{{ $order->status }}</td>
                                <td>{{ $order->transaction_id }}</td>
                                <td>{{ $order->transaction->first()->payu_id }}</td>
                                <td>{{ $order->created_at }}</td>
                                <td>
                                    {{ link_to_route('admin.orders.show', 'Administrar', [$order->id], ['class' => 'btn btn-info']) }}
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="4">No tienes pedidos</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
@stop

app/views/admin/orders/show.blade.php
@extends('default')

@section('location')
Administraci&oacute; de Pedido # {{ $order->id }}
@stop

@section('addedcss')
@parent
<style media="screen">
.shipment_id {
    display: none;
}
</style>
@stop

@section('content')
<section class="main-body">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h2>Informacion Pedido</h2>
                <p>Usuario:
                    <span>{{ link_to_route('users.show', $order->user->name, ['users' => $order->user->username] ) }}</span>
                </p>
                <p>Estado:
                    <span>{{ $order->status }}</span>
                </p>
                <p>ID Transaccion PayU:
                    <span>{{ $order->transaction->first()->payu_id }}</span>
                </p>
                <p>Fecha:
                    <span>{{ $order->created_at }}</span>
                </p>
                <div class="row">
                    <div class="col-xs-12" style="overflow:auto">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Publicaci&oacute;n</th>
                                    <th>Estado</th>
                                    <th>Guia de Envio</th>
                                    <th>Fecha Creaci&oacute;n</th>
                                    <th>Fecha Actualizaci&oacute;n</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($order->shipments as $key => $shipment)
                                    <tr>
                                        <td>
                                            {{ link_to_route(
                                                'users.publications.show',
                                                $shipment->publication->published_book_title,
                                                [
                                                    'users' => $shipment->publication->user->username,
                                                    'publications' => $shipment->publication->id
                                                ]) }}
                                        </td>
                                        <td>{{ $shipment->status }}</td>
                                        <td>{{ $shipment->identifier }}</td>
                                        <td>{{ $shipment->created_at }}</td>
                                        <td>{{ $shipment->updated_at }}</td>
                                        <td>
                                            <button type="button" role="button"
                                                class="btn btn-primary btn-shipment"
                                                data-shipment-id="{{ $shipment->id }}"
                                                data-shipment-status="{{ $shipment->shipment_status }}"
                                                data-shipment-identifier="{{ $shipment->identifier }}"
                                                data-shipment-publication="{{ e(json_encode($shipment->publication)) }}">
                                                <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span>
                                            </button>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="4">No tienes pedidos</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>
@stop

@section('addedjs')
@parent
<script type="text/javascript">
(function () {
    var statuses = [];
    $.ajax({
        url: '{{ route('orders.shipment_statuses') }}'
    }).done(function (response) {
        statuses = response.map(function (item, idx, array) {
            return $("<option/>",{
                value: item.id,
                text: item.description
            });
        });
    }).fail(function (request, state) {
        KINBU.Notification.error(state + " " + request.status + ": "+ request.statusText);
    });
    $("button.btn-shipment").on('click', function (e) {
        var shipmentPublication = $(this).data('shipmentPublication'); console.log(shipmentPublication);
        var p_shipment_user = $("<p />", {
            text: "Vendedor: "
        }).append($("<span />").append($("<a />", {
            href: ("/users/" + shipmentPublication.user.username),
            text: shipmentPublication.user.name
        })));
        var p_shipment_fullname = $("<p />", {
            text: "Nombre completo: "
        }).append($("<span />", {
            text: shipmentPublication.pickup_fullname
        }));
        var p_shipment_address = $("<p />", {
            text: "Direccion: "
        }).append($("<span />", {
            text: shipmentPublication.pickup_address
        }));
        var p_shipment_phone = $("<p />", {
            text: "Telefono: "
        }).append($("<span />", {
            text: shipmentPublication.pickup_phone
        }));
        var p_shipment_city = $("<p />", {
            text: "Ciudad: "
        }).append($("<span />", {
            text: shipmentPublication.pickup_city
        }));
        var p_shipment_account = $("<p />", {
            text: "Numero de cuenta: "
        }).append($("<span />", {
            text: shipmentPublication.user.person.account_number
        }));
        var div_shipment = $("<div />").append([p_shipment_user, p_shipment_fullname, p_shipment_address, p_shipment_phone, p_shipment_city, p_shipment_account]);
        var shipmentId = $(this).data('shipmentId');
        var shipmentStatus = $(this).data('shipmentStatus');
        var shipmentIdentifier = $(this).data('shipmentIdentifier');
        var btn_ok = $("<button/>",{
            type: 'button',
            class: 'btn btn-primary',
            'data-dismiss': 'modal',
            text: 'Aceptar'
        });
        var btn_cerrar = $("<button/>",{
            type: 'button',
            class: 'btn btn-default',
            'data-dismiss': 'modal',
            text: 'Cerrar'
        });
        $(btn_ok).on('click', function (e) {
            $.ajax({
                method: 'GET',
                url: document.URL + '/shipment_update/' + shipmentId,
                data: {
                    status: shipmentStatus,
                    identifier: shipmentIdentifier
                }
            }).done(function (response) {
                KINBU.Notification.show(response.message);
                setTimeout( function(){location.reload(true);}, 2000);

            }).fail(function (request, state) {
                KINBU.Notification.error(state + " " + request.status + ": "+ request.statusText);
            });
        });
        var identifier = $("<input/>",{
            type: 'text',
            class: 'form-control',
            placeholder: 'Identificador de envio',
            value: shipmentIdentifier
        });

        $(identifier).on('input', function (e, a, b, c, d) {
            shipmentIdentifier = $(identifier).val();
        });

        var status = $("<select />",{
            class: 'form-control'
        }).append(statuses);
        status.val(shipmentStatus);

        $(status).on('change', function (e) {
            shipmentStatus = $(status).val();
        });

        KINBU.Msg.create("Administraci&oacute;n de env&iacute;o", [div_shipment, identifier, status], [btn_ok, btn_cerrar]);
    });
}());
</script>
@endsection